<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>obj_FilterPanel_Button</name>
   <tag></tag>
   <elementGuidId>1db0c4e2-bdd4-4146-be78-0ad68f7458f9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'open-filter-panel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>open-filter-panel</value>
      <webElementGuid>08e8d7bd-f335-46cb-be66-992e8158c7f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
